/* eslint-disable */
import * as process from 'process';
import { z } from 'zod';

export const NEXT_PUBLIC_API_ENDPOINT = process.env.NEXT_PUBLIC_API_ENDPOINT;

// export const NEXT_PUBLIC_ENVIRONMENT = process.env.NEXT_PUBLIC_ENVIRONMENT;
export const NEXT_PUBLIC_PROJECT_ID = process.env.NEXT_PUBLIC_PROJECT_ID;

export const NEXT_PUBLIC_SUPPORTED_CHAINS =
    process.env.NEXT_PUBLIC_SUPPORTED_CHAINS;

export const NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_NAME =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_NAME;

export const NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_ID =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_ID;

export const NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_RPC =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_RPC;

export const NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CHAIN_EXPLORER;

export const NEXT_PUBLIC_BASE_SEPOLIA_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_BASE_SEPOLIA_CONTRACT_ADDRESS_PROD =
    process.env.NEXT_PUBLIC_BASE_SEPOLIA_CONTRACT_ADDRESS_PROD;

export const NEXT_PUBLIC_POLYGON_AMOY_CHAIN_NAME =
    process.env.NEXT_PUBLIC_POLYGON_AMOY_CHAIN_NAME;

export const NEXT_PUBLIC_POLYGON_AMOY_CHAIN_ID =
    process.env.NEXT_PUBLIC_POLYGON_AMOY_CHAIN_ID;

export const NEXT_PUBLIC_POLYGON_AMOY_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_POLYGON_AMOY_CHAIN_EXPLORER;
export const NEXT_PUBLIC_POLYGON_AMOY_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_POLYGON_AMOY_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_ARTELA_CHAIN_NAME =
    process.env.NEXT_PUBLIC_ARTELA_CHAIN_NAME;
export const NEXT_PUBLIC_ARTELA_CHAIN_ID =
    process.env.NEXT_PUBLIC_ARTELA_CHAIN_ID;
export const NEXT_PUBLIC_ARTELA_CHAIN_RPC =
    process.env.NEXT_PUBLIC_ARTELA_CHAIN_RPC;
export const NEXT_PUBLIC_ARTELA_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_ARTELA_CHAIN_EXPLORER;
export const NEXT_PUBLIC_ARTELA_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_ARTELA_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_NAME =
    process.env.NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_NAME;
export const NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_ID =
    process.env.NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_ID;
export const NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_RPC =
    process.env.NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_RPC;
export const NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_UNICHAIN_SEPOLIA_CHAIN_EXPLORER;
export const NEXT_PUBLIC_UNICHAIN_SEPOLIA_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_UNICHAIN_SEPOLIA_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_BASE_CHAIN_NAME =
    process.env.NEXT_PUBLIC_BASE_CHAIN_NAME;
export const NEXT_PUBLIC_BASE_CHAIN_ID = process.env.NEXT_PUBLIC_BASE_CHAIN_ID;
export const NEXT_PUBLIC_BASE_CHAIN_RPC =
    process.env.NEXT_PUBLIC_BASE_CHAIN_RPC;
export const NEXT_PUBLIC_BASE_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_BASE_CHAIN_EXPLORER;
export const NEXT_PUBLIC_BASE_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_BASE_CONTRACT_ADDRESS;
export const NEXT_PUBLIC_BASE_CONTRACT_ADDRESS_PROD =
    process.env.NEXT_PUBLIC_BASE_CONTRACT_ADDRESS_PROD;

export const NEXT_PUBLIC_IOTA_CHAIN_NAME =
    process.env.NEXT_PUBLIC_IOTA_CHAIN_NAME;
export const NEXT_PUBLIC_IOTA_CHAIN_ID = process.env.NEXT_PUBLIC_IOTA_CHAIN_ID;
export const NEXT_PUBLIC_IOTA_CHAIN_RPC =
    process.env.NEXT_PUBLIC_IOTA_CHAIN_RPC;
export const NEXT_PUBLIC_IOTA_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_IOTA_CHAIN_EXPLORER;
export const NEXT_PUBLIC_IOTA_CONTRACT_ADDRESS_PROD =
    process.env.NEXT_PUBLIC_IOTA_CONTRACT_ADDRESS_PROD;

export const NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_NAME =
    process.env.NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_NAME;
export const NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_ID =
    process.env.NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_ID;
export const NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_RPC =
    process.env.NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_RPC;
export const NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_BERACHAIN_MAINNET_CHAIN_EXPLORER;
export const NEXT_PUBLIC_BERACHAIN_MAINNET_CONTRACT_ADDRESS_PROD =
    process.env.NEXT_PUBLIC_BERACHAIN_MAINNET_CONTRACT_ADDRESS_PROD;

export const NEXT_PUBLIC_API_ENDPOINT_PROD =
    process.env.NEXT_PUBLIC_API_ENDPOINT_PROD;

export const NEXT_PUBLIC_MONAD_CHAIN_NAME =
    process.env.NEXT_PUBLIC_MONAD_CHAIN_NAME;
export const NEXT_PUBLIC_MONAD_CHAIN_ID =
    process.env.NEXT_PUBLIC_MONAD_CHAIN_ID;
export const NEXT_PUBLIC_MONAD_CHAIN_RPC =
    process.env.NEXT_PUBLIC_MONAD_CHAIN_RPC;
export const NEXT_PUBLIC_MONAD_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_MONAD_CHAIN_EXPLORER;
export const NEXT_PUBLIC_MONAD_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_MONAD_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_SOMNIA_CHAIN_NAME =
    process.env.NEXT_PUBLIC_SOMNIA_CHAIN_NAME;
export const NEXT_PUBLIC_SOMNIA_CHAIN_ID =
    process.env.NEXT_PUBLIC_SOMNIA_CHAIN_ID;
export const NEXT_PUBLIC_SOMNIA_CHAIN_RPC =
    process.env.NEXT_PUBLIC_SOMNIA_CHAIN_RPC;
export const NEXT_PUBLIC_SOMNIA_CHAIN_EXPLORER =
    process.env.NEXT_PUBLIC_SOMNIA_CHAIN_EXPLORER;
export const NEXT_PUBLIC_SOMNIA_CONTRACT_ADDRESS =
    process.env.NEXT_PUBLIC_SOMNIA_CONTRACT_ADDRESS;

export const NEXT_PUBLIC_IS_FAUCET = process.env.NEXT_PUBLIC_IS_FAUCET;

export const LOG_LEVEL_SCHEMA = z
    .enum(['trace', 'debug', 'info', 'warn', 'error', 'fatal', 'silent'])
    .default('info');

export const LOG_LEVEL = LOG_LEVEL_SCHEMA.parse(
    process.env.LOG_LEVEL ?? 'info'
);

export const isDev = process.env.NODE_ENV === 'development';
export const isProd = process.env.NODE_ENV === 'production';
